package com.classmate.server.model;

import java.util.Date;

public class Pass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.id
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.title
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.uName
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.hostUrl
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private String hosturl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.pwd
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.createTime
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pass.updateTime
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.id
     *
     * @return the value of t_pass.id
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.id
     *
     * @param id the value for t_pass.id
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.title
     *
     * @return the value of t_pass.title
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.title
     *
     * @param title the value for t_pass.title
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.uName
     *
     * @return the value of t_pass.uName
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.uName
     *
     * @param uname the value for t_pass.uName
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.hostUrl
     *
     * @return the value of t_pass.hostUrl
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public String getHosturl() {
        return hosturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.hostUrl
     *
     * @param hosturl the value for t_pass.hostUrl
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setHosturl(String hosturl) {
        this.hosturl = hosturl == null ? null : hosturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.pwd
     *
     * @return the value of t_pass.pwd
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.pwd
     *
     * @param pwd the value for t_pass.pwd
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.createTime
     *
     * @return the value of t_pass.createTime
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.createTime
     *
     * @param createtime the value for t_pass.createTime
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pass.updateTime
     *
     * @return the value of t_pass.updateTime
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pass.updateTime
     *
     * @param updatetime the value for t_pass.updateTime
     *
     * @mbg.generated Sun May 06 22:59:34 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}