package com.classmate.server.model;

import java.util.Date;

public class Picture {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.id
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.albumId
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private Integer albumid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.userId
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.url
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.createTime
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.updateTime
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column picture.clickCount
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	private Integer clickcount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.id
	 * @return  the value of picture.id
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.id
	 * @param id  the value for picture.id
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.albumId
	 * @return  the value of picture.albumId
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public Integer getAlbumid() {
		return albumid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.albumId
	 * @param albumid  the value for picture.albumId
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setAlbumid(Integer albumid) {
		this.albumid = albumid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.userId
	 * @return  the value of picture.userId
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.userId
	 * @param userid  the value for picture.userId
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.url
	 * @return  the value of picture.url
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.url
	 * @param url  the value for picture.url
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.createTime
	 * @return  the value of picture.createTime
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.createTime
	 * @param createtime  the value for picture.createTime
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.updateTime
	 * @return  the value of picture.updateTime
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.updateTime
	 * @param updatetime  the value for picture.updateTime
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column picture.clickCount
	 * @return  the value of picture.clickCount
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public Integer getClickcount() {
		return clickcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column picture.clickCount
	 * @param clickcount  the value for picture.clickCount
	 * @mbggenerated  Fri Jul 21 15:18:36 CST 2017
	 */
	public void setClickcount(Integer clickcount) {
		this.clickcount = clickcount;
	}
}